# Generated by Django 5.1.5 on 2025-06-16 08:09

import datetime
import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the sender.', max_length=100)),
                ('email', models.EmailField(help_text='Email address of the sender.', max_length=254)),
                ('subject', models.CharField(help_text='Subject of the message.', max_length=200)),
                ('message', models.TextField(help_text='The content of the message.')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False, help_text='Mark as read once processed.')),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('proficiency', models.IntegerField(help_text='Proficiency percentage (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('icon', models.CharField(blank=True, help_text="FontAwesome or other icon class for visual representation (e.g., 'fa-python')", max_length=50)),
                ('description', models.TextField(blank=True, help_text='A brief description of the skill.')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['-proficiency'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('role', models.CharField(blank=True, help_text="Author's role or company (e.g., 'CEO of Example Corp').", max_length=100)),
                ('content', models.TextField(help_text='The actual testimonial text.')),
                ('image', models.ImageField(blank=True, help_text='Optional profile picture of the testimonial author.', null=True, upload_to='testimonials/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Check to display this testimonial prominently.')),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='phone number')),
                ('username', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Custom User',
                'verbose_name_plural': 'Custom Users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='Auto-generated from title.', unique=True)),
                ('content', models.TextField(help_text='The full content of the blog post. Can contain HTML.')),
                ('category', models.CharField(choices=[('web_dev', 'Web Development'), ('design', 'Design'), ('career', 'Career'), ('tutorial', 'Tutorial'), ('personal', 'Personal'), ('tech_review', 'Technology Review')], default='web_dev', max_length=50)),
                ('image', models.ImageField(blank=True, help_text='Main image/cover for the blog post.', null=True, upload_to='blog_covers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=False, help_text='Check to make the post publicly visible.')),
                ('tags', models.CharField(blank=True, help_text="Comma-separated tags for search and filtering (e.g., 'Django, Frontend, Tutorial').", max_length=200)),
                ('access_level', models.CharField(choices=[('public', 'Public'), ('registered', 'Registered Users Only'), ('private', 'Private (Admin Only)')], default='public', help_text='Who can view this blog post?', max_length=20)),
                ('author', models.ForeignKey(blank=True, help_text='The author of this blog post.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(help_text='Author(s) of the book.', max_length=255)),
                ('isbn', models.CharField(blank=True, help_text='International Standard Book Number (ISBN-13).', max_length=13, null=True, unique=True)),
                ('genre', models.CharField(blank=True, help_text="Genre of the book (e.g., 'Fiction', 'Non-fiction', 'Technology').", max_length=100)),
                ('description', models.TextField(blank=True, help_text='A brief summary or review of the book.')),
                ('cover_image', models.ImageField(blank=True, help_text='Cover image of the book.', null=True, upload_to='book_covers/')),
                ('purchase_link', models.URLField(blank=True, help_text="Link to purchase the book (e.g., Amazon, publisher's site).")),
                ('published_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Check to feature this book prominently.')),
                ('access_level', models.CharField(choices=[('public', 'Public'), ('registered', 'Registered Users Only')], default='public', help_text='Who can view this book listing?', max_length=20)),
                ('recommended_by', models.ForeignKey(blank=True, help_text='The user who recommended this book (likely yourself).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended_books', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True, help_text='A brief description of the document.')),
                ('file', models.FileField(help_text='Upload your PDF, PPT, or other relevant document.', upload_to='documents/')),
                ('document_type', models.CharField(choices=[('pdf', 'PDF Document'), ('slides', 'Presentation Slides'), ('ebook', 'E-Book'), ('other', 'Other')], default='pdf', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=False, help_text='Check to make the document publicly downloadable.')),
                ('access_level', models.CharField(choices=[('public', 'Public'), ('registered', 'Registered Users Only'), ('private', 'Private (Admin Only)')], default='registered', help_text='Who can access/download this document?', max_length=20)),
                ('owner', models.ForeignKey(blank=True, help_text='The user who uploaded this document.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Name or topic of the meeting/lecture.', max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='Auto-generated from title.', unique=True)),
                ('description', models.TextField(help_text='Detailed agenda or description of the meeting.')),
                ('meeting_type', models.CharField(choices=[('1-on-1', 'One-on-One Consultation'), ('group_lecture', 'Group Lecture/Webinar'), ('discovery_call', 'Discovery Call'), ('other', 'Other')], default='1-on-1', max_length=20)),
                ('date', models.DateField(default=datetime.date.today, help_text='Date of the meeting.')),
                ('start_time', models.TimeField(help_text='Start time of the meeting (e.g., 14:00).')),
                ('end_time', models.TimeField(blank=True, help_text='End time of the meeting (optional).', null=True)),
                ('duration_minutes', models.IntegerField(blank=True, help_text='Duration in minutes.', null=True)),
                ('meeting_link', models.URLField(blank=True, help_text='Link to the video conferencing room.')),
                ('max_attendees', models.IntegerField(blank=True, help_text='Maximum number of participants allowed (for group lectures).', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('is_active', models.BooleanField(default=True, help_text='Is this meeting slot currently available for booking?')),
                ('requires_registration', models.BooleanField(default=True, help_text='Does this meeting require users to register?')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Optional: Price for this meeting slot (e.g., for consultations).', max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendees', models.ManyToManyField(blank=True, help_text='Users who have booked/registered for this meeting.', related_name='booked_meetings', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(help_text='The user offering this meeting/lecture (likely you).', on_delete=django.db.models.deletion.CASCADE, related_name='offered_meetings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meeting/Lecture',
                'verbose_name_plural': 'Meetings/Lectures',
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('content', models.TextField(help_text='The content of the note. Can contain HTML.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=False, help_text='Should this note be publicly visible?')),
                ('access_level', models.CharField(choices=[('public', 'Public'), ('registered', 'Registered Users Only'), ('private', 'Private (Author Only)')], default='registered', help_text='Who can view this note?', max_length=20)),
                ('author', models.ForeignKey(help_text='The author of this note.', on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='Auto-generated from title.', unique=True)),
                ('description', models.TextField(help_text='Detailed description of the project.')),
                ('image', models.ImageField(blank=True, help_text='Thumbnail or main image for the project.', null=True, upload_to='projects/')),
                ('url', models.URLField(blank=True, help_text='Link to live project demo or GitHub repository.')),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('in_progress', 'In Progress'), ('planned', 'Planned'), ('archived', 'Archived')], default='completed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tags', models.CharField(blank=True, help_text="Comma-separated tags (e.g., 'Django, Tailwind CSS, Python').", max_length=200)),
                ('is_featured', models.BooleanField(default=False, help_text='Check if this project should be featured on the homepage.')),
                ('skills_used', models.ManyToManyField(blank=True, help_text='Skills applied in this project.', related_name='projects', to='portfolio.skill')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-created_at'],
            },
        ),
    ]
