# Generated by Django 5.2.4 on 2026-01-24 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('short_description', models.TextField(blank=True, max_length=300)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='course_banners/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='course_thumbnails/')),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived')], default='upcoming', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('schedule_note', models.TextField(blank=True, help_text='e.g., Mon-Fri 1-4pm ET')),
                ('location', models.CharField(blank=True, max_length=255)),
                ('is_virtual', models.BooleanField(default=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('is_free', models.BooleanField(default=True)),
                ('access_level', models.CharField(choices=[('public', 'Public'), ('registered', 'Registered Users'), ('enrolled', 'Enrolled Students Only')], default='enrolled', max_length=20)),
                ('prerequisites', models.TextField(blank=True)),
                ('learning_objectives', models.JSONField(blank=True, default=list, help_text='List of learning objectives')),
                ('enrolled_count', models.IntegerField(default=0)),
                ('completion_rate', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('books', models.ManyToManyField(blank=True, related_name='courses', to='portfolio.book')),
                ('documents', models.ManyToManyField(blank=True, related_name='courses', to='portfolio.document')),
                ('meetings', models.ManyToManyField(blank=True, related_name='courses', to='portfolio.meeting')),
                ('notes', models.ManyToManyField(blank=True, related_name='courses', to='portfolio.note')),
                ('projects', models.ManyToManyField(blank=True, related_name='courses', to='portfolio.project')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='portfolio.course')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('role', models.CharField(blank=True, max_length=100)),
                ('is_lead_instructor', models.BooleanField(default=False)),
                ('twitter_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('website_url', models.URLField(blank=True)),
                ('courses', models.ManyToManyField(blank=True, related_name='instructors', to='portfolio.course')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Instructor',
                'verbose_name_plural': 'Instructors',
            },
        ),
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('progress_data', models.JSONField(blank=True, default=dict)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='portfolio.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Course Enrollment',
                'verbose_name_plural': 'Course Enrollments',
                'unique_together': {('user', 'course')},
            },
        ),
        migrations.CreateModel(
            name='CourseModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('is_live_session', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('slides_url', models.URLField(blank=True)),
                ('video_url', models.URLField(blank=True)),
                ('code_url', models.URLField(blank=True)),
                ('additional_resources', models.JSONField(blank=True, default=list)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='portfolio.course')),
                ('documents', models.ManyToManyField(blank=True, to='portfolio.document')),
                ('lecture_meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.meeting')),
                ('notes', models.ManyToManyField(blank=True, to='portfolio.note')),
                ('projects', models.ManyToManyField(blank=True, to='portfolio.project')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('course', 'order')},
            },
        ),
        migrations.CreateModel(
            name='UserCourseProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_key', models.CharField(help_text='Identifier for the course', max_length=100)),
                ('enrollment_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('progress_data', models.JSONField(default=dict, help_text='Stores completion status and progress metrics')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Course Progress',
                'verbose_name_plural': 'Course Progress Records',
                'unique_together': {('user', 'course_key')},
            },
        ),
    ]
